"""create new tables

Revision ID: 81cd88ecd379
Revises: f01df230acdc
Create Date: 2025-07-24 11:36:54.874166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '81cd88ecd379'
down_revision: Union[str, Sequence[str], None] = 'f01df230acdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivelabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('label', AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('text', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archiveentry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivelabel_id'), 'archivelabel', ['id'], unique=False)
    op.drop_table('archivemetadata')
    op.create_index(op.f('ix_archivecontent_id'), 'archivecontent', ['id'], unique=False)
    op.create_index(op.f('ix_archiveentry_id'), 'archiveentry', ['id'], unique=False)
    op.create_index(op.f('ix_posting_id'), 'posting', ['id'], unique=False)
    op.create_index(op.f('ix_postinglink_id'), 'postinglink', ['id'], unique=False)
    op.create_index(op.f('ix_postingpage_id'), 'postingpage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postingpage_id'), table_name='postingpage')
    op.drop_index(op.f('ix_postinglink_id'), table_name='postinglink')
    op.drop_index(op.f('ix_posting_id'), table_name='posting')
    op.drop_index(op.f('ix_archiveentry_id'), table_name='archiveentry')
    op.drop_index(op.f('ix_archivecontent_id'), table_name='archivecontent')
    op.create_table('archivemetadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('archive_id', sa.INTEGER(), nullable=False),
    sa.Column('start_position', sa.INTEGER(), nullable=False),
    sa.Column('end_position', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archiveentry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_archivelabel_id'), table_name='archivelabel')
    op.drop_table('archivelabel')
    # ### end Alembic commands ###
