"""Initial Migration

Revision ID: f01df230acdc
Revises: 
Create Date: 2025-07-20 16:20:16.465557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f01df230acdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivecontent', sa.Column('is_inference_done', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivecontent', 'is_inference_done')
    # ### end Alembic commands ###
