name: Entity Recognition
run-name: Entity Recognition with GLiNER (uv script)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
    get-scraper-run-id:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        outputs:
            RUN_ID: ${{ steps.find-run-id.outputs.RUN_ID }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Find run id for latest sqlite export
              id: find-run-id
              run: |
                  export RUN_ID=$(gh run list -s success --workflow=gather-place-links.yml --json databaseId --limit 1 --jq ".[].databaseId")
                  echo "RUN_ID=${RUN_ID}" >> $GITHUB_OUTPUT

    entity-recognition:
      needs: get-scraper-run-id
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Download SQLite database from artifacts
          uses: actions/download-artifact@v4
          with:
              github-token: ${{ secrets.GH_ACTIONS_TOKEN }}
              run-id: ${{ needs.get-scraper-run-id.outputs.RUN_ID }}
              name: sqlite-database-after-fetch-archives
        - name: Download archive contents
          run: |
              ls -la
              uv venv
              source .venv/bin/activate
              uv sync
              openplace bulk-export-archive-contents --limit 100 --output-dir . --silent
              ls -la
        - name: Download GLiNER uv script from Gist & run it
          env:
              GH_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          run: |
              export GH_GIST_ID=$(gh gist list --filter "GLiNER" | tail -n 1 | cut -f1)
              gh gist clone $GH_GIST_ID gliner-gist
              ls gliner-gist
              cp gliner-gist/* .
              ls -la
              labels=()
              labels+=("critere_de_selection_ou_exigence")
              labels+=("duree_du_projet")
              labels+=("date_limite_candidature")
              labels+=("type_de_livrable")
              labels+=("prix_ou_budget_prevu_en_euros")
              LABELS_FILE=labels.txt
              for label in "${labels[@]}"; do
                  echo $label >> $LABELS_FILE
              done
              cat $LABELS_FILE
              chmod +x gliner-infer-labels
              echo "Doing a dry run to cache dependencies..."
              ./gliner-infer-labels --help > /dev/null 2>&1 || echo "GLiNER not found"
              for file in *.txt; do
                  fname=$(basename $file)
                  echo "Processing $fname"
                  ./gliner-infer-labels --model="knowledgator/gliner-x-large" $file $LABELS_FILE > $fname.jsonl
                  cat $fname.jsonl
                  echo "--------------------------------"
              done