name: Gather Place Links
run-name: Gathering Place Links
on: [push]
jobs:
  gather-place-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: sync package with uv
        run: |
            uv venv
            source .venv/bin/activate
            uv sync
            openplace discover
            ls -la
      - name: Push sqlite database to artifacts
        uses: actions/upload-artifact@v4
        with:
            name: sqlite-database-after-discover
            path: openplace.db

  fetch-place-links:
    runs-on: ubuntu-latest
    needs: gather-place-links # TODO: this step isn't required strictly speaking, if the db artifact exists, we can just use that
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download sqlite database backup
        uses: actions/download-artifact@v4
        with:
            name: sqlite-database-after-discover
      - name: Fetch place links
        run: |
            uv venv
            source .venv/bin/activate
            uv sync
            openplace fetch-archives
            openplace export-archives
      - name: Compress ZIPs into single tar.xz file
        run: |
            tar -Jcf place-documents.tar.xz *.zip
      - name: Upload tar.xz file to artifacts
        uses: actions/upload-artifact@v4
        with:
            name: place-documents
            path: place-documents.tar.xz
      - name: Upload updated db to artifacts
        uses: actions/upload-artifact@v4
        with:
            name: sqlite-database-after-fetch-archives
            path: openplace.db
      - name: Upload parquet metadata to artifacts
        uses: actions/upload-artifact@v4
        with:
            name: place-metadata
            path: archives*.parquet

  upload-to-gh-releases:
    runs-on: ubuntu-latest
    needs: fetch-place-links
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: download all previous artifacts
        uses: actions/download-artifact@v4
      - name: upload to gh releases
        env:
            GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
            ls -al
            unzip *.zip
            ls -al
            gh release upload ${{ github.ref_name }} place-documents.tar.xz --clobber
            gh release upload ${{ github.ref_name }} place-metadata.parquet --clobber