name: Publish Python Wheels using uv
run-name: ${{ github.actor }} is publishing Python Wheels using uv 🚀
on: [push]
jobs:
  publish-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/uv@v6
      - name: Build Python wheels
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e .[dev]
      - name: Build Python wheels
        run: uv build --refresh --wheel --sdist --package openplace
      - name: Publish Python wheels to github releases
        run: |
          echo "Tag will be ${{ github.ref_name }}"
          echo "Token is ${{ secrets.GITHUB_TOKEN }}"
          echo "Repository is ${{ github.repository }}"
          echo "Repository owner is ${{ github.repository_owner }}"
          echo "Repository owner is ${{ github.repository_owner }}"


