name: Publish Python Wheels using uv
run-name: ${{ github.actor }} is publishing Python Wheels using uv 🚀
on: [push]
jobs:
  publish-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Python wheels and publish to github releases
        run: uv build --refresh --wheel --sdist --package openplace
      - name: Publish Python wheels to github releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          echo "Tag will be ${{ github.ref_name }}"
          export TAG_EXISTS=$(gh release view ${{ github.ref_name }} 2>&1 > /dev/null)
          if [ -z "$TAG_EXISTS" ]; then
            gh release create ${{ github.ref_name }} --generate-notes
          else
            gh release upload ${{ github.ref_name }} openplace/dist/*.whl --clobber
          fi
          echo "Published ${{ github.ref_name }} to github releases"
        