name: Publish Python Wheels using uv
run-name: ${{ github.actor }} is publishing Python Wheels using uv 🚀
on: [push]
jobs:
  publish-wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Python wheels and publish to github releases
        run: uv build --refresh --wheel --sdist --package openplace
      - name: Publish Python wheels to github releases
        run: |
          echo "Tag will be ${{ github.ref_name }}"
          echo "Token is ${{ secrets.GITHUB_TOKEN }}"
          echo "Repository is ${{ github.repository }}"
          echo "Repository owner is ${{ github.repository_owner }}"
          echo "Repository owner is ${{ github.repository_owner }}"


